version: 0.0
os: linux
files:
  - source: /
    destination: /var/node/google-notion-sync
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root