version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 19
    commands:
      - echo Installing node...
  pre-build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo Building the Node code...
      - npm run test
  post-build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
