branch-defaults:
  main:
    environment: Googlenotionsynceb-env
environment-defaults:
  Googlenotionsynceb-env:
    branch: null
    repository: null
global:
  application_name: Google-Notion-Sync-EB
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
